In [83]:
import pandas as pd
import numpy as np
print(pd.__version__)

2.2.3

In [84]:
s = pd.Series([1,2,3,4])

In [85]:
s

0    1
1    2
2    3
3    4
dtype: int64

In [86]:
s = pd.Series([1,2,3,4],index=['a','b','c','d'])

In [87]:
s

a    1
b    2
c    3
d    4
dtype: int64

In [88]:
s = pd.Series({
    "hridoy":'Baby I Need You In My Life',
    'She':'Fuck Off'
})

In [89]:
s

hridoy    Baby I Need You In My Life
She                         Fuck Off
dtype: object

In [90]:

s = pd.DataFrame({
    "hridoy":['Baby I Need You In My Life'],
    "She":['Fuck Off']
},index=[1])

In [91]:
s

                       hridoy       She
1  Baby I Need You In My Life  Fuck Off

In [92]:
# Creating DataFrame from dictionary
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'Diana'],
    'Age': [25, 30, 35, 28],
    'City': ['New York', 'London', 'Tokyo', 'Paris'],
    'Salary': [50000, 60000, 70000, 55000]
}
df = pd.DataFrame(data)
df

      Name  Age      City  Salary
0    Alice   25  New York   50000
1      Bob   30    London   60000
2  Charlie   35     Tokyo   70000
3    Diana   28     Paris   55000

In [93]:
listt = [['himu',24],['hridoy',24]]
d = pd.DataFrame(listt,columns=['Name','Age']
                 )

In [94]:
d

     Name  Age
0    himu   24
1  hridoy   24

In [95]:
np = pd.DataFrame(np.arange(16).reshape(4,4))

In [96]:
np

    0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [97]:
df.shape

(4, 4)

In [98]:
df.size

16

In [99]:
df.index

RangeIndex(start=0, stop=4, step=1)

In [100]:
df.columns

Index(['Name', 'Age', 'City', 'Salary'], dtype='object')

In [101]:
df.describe()

             Age        Salary
count   4.000000      4.000000
mean   29.500000  58750.000000
std     4.203173   8539.125638
min    25.000000  50000.000000
25%    27.250000  53750.000000
50%    29.000000  57500.000000
75%    31.250000  62500.000000
max    35.000000  70000.000000

In [102]:
df.dtypes

Name      object
Age        int64
City      object
Salary     int64
dtype: object

In [103]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      object
 1   Age     4 non-null      int64
 2   City    4 non-null      object
 3   Salary  4 non-null      int64
dtypes: int64(2), object(2)
memory usage: 260.0+ bytes

In [104]:
df.head()

      Name  Age      City  Salary
0    Alice   25  New York   50000
1      Bob   30    London   60000
2  Charlie   35     Tokyo   70000
3    Diana   28     Paris   55000

In [105]:
df.tail()

      Name  Age      City  Salary
0    Alice   25  New York   50000
1      Bob   30    London   60000
2  Charlie   35     Tokyo   70000
3    Diana   28     Paris   55000

In [106]:
df.ndim

2

In [107]:
df.values

array([['Alice', 25, 'New York', 50000],
       ['Bob', 30, 'London', 60000],
       ['Charlie', 35, 'Tokyo', 70000],
       ['Diana', 28, 'Paris', 55000]], dtype=object)

In [108]:
df.index

RangeIndex(start=0, stop=4, step=1)

In [109]:
df.index

RangeIndex(start=0, stop=4, step=1)

In [110]:
df

      Name  Age      City  Salary
0    Alice   25  New York   50000
1      Bob   30    London   60000
2  Charlie   35     Tokyo   70000
3    Diana   28     Paris   55000

In [111]:
df.rename(columns={'Name':'Full_Name'})

  Full_Name  Age      City  Salary
0     Alice   25  New York   50000
1       Bob   30    London   60000
2   Charlie   35     Tokyo   70000
3     Diana   28     Paris   55000

In [112]:
df.rename(columns=str.lower)

      name  age      city  salary
0    Alice   25  New York   50000
1      Bob   30    London   60000
2  Charlie   35     Tokyo   70000
3    Diana   28     Paris   55000

In [113]:
df.rename(columns=str.lower,inplace=True)

In [114]:
df.set_index('name')

         age      city  salary
name
Alice     25  New York   50000
Bob       30    London   60000
Charlie   35     Tokyo   70000
Diana     28     Paris   55000

In [115]:
df.set_index(['name', 'age'])

                 city  salary
name    age
Alice   25   New York   50000
Bob     30     London   60000
Charlie 35      Tokyo   70000
Diana   28      Paris   55000

In [116]:
df.dtypes.value_counts()

object    2
int64     2
Name: count, dtype: int64

In [117]:
df.memory_usage(deep=True)

Index     132
name      216
age        32
city      220
salary     32
dtype: int64

In [118]:
import seaborn as sns

In [119]:
df = sns.load_dataset('tips')

In [120]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [121]:
df[['tip','sex']].head(3)

    tip     sex
0  1.01  Female
1  1.66    Male
2  3.50    Male

In [122]:
df.iloc[1:3,2:]

    sex smoker  day    time  size
1  Male     No  Sun  Dinner     3
2  Male     No  Sun  Dinner     3

In [123]:
df.loc[:,['tip']]

      tip
0    1.01
1    1.66
2    3.50
3    3.31
4    3.61
..    ...
239  5.92
240  2.00
241  2.00
242  1.75
243  3.00

[244 rows x 1 columns]

In [124]:
df[(df['tip']>df['tip'].mean())& (df['sex']=='Male')]

     total_bill   tip   sex smoker  day    time  size
2         21.01  3.50  Male     No  Sun  Dinner     3
3         23.68  3.31  Male     No  Sun  Dinner     2
5         25.29  4.71  Male     No  Sun  Dinner     4
7         26.88  3.12  Male     No  Sun  Dinner     4
9         14.78  3.23  Male     No  Sun  Dinner     2
..          ...   ...   ...    ...  ...     ...   ...
227       20.45  3.00  Male     No  Sat  Dinner     4
231       15.69  3.00  Male    Yes  Sat  Dinner     3
232       11.61  3.39  Male     No  Sat  Dinner     2
234       15.53  3.00  Male    Yes  Sat  Dinner     2
239       29.03  5.92  Male     No  Sat  Dinner     3

[82 rows x 7 columns]

In [125]:
df.query('tip>5 and size>3')

     total_bill   tip     sex smoker   day    time  size
23        39.42  7.58    Male     No   Sat  Dinner     4
44        30.40  5.60    Male     No   Sun  Dinner     4
47        32.40  6.00    Male     No   Sun  Dinner     4
52        34.81  5.20  Female     No   Sun  Dinner     4
59        48.27  6.73    Male     No   Sat  Dinner     4
85        34.83  5.17  Female     No  Thur   Lunch     4
116       29.93  5.07    Male     No   Sun  Dinner     4
141       34.30  6.70    Male     No  Thur   Lunch     6
155       29.85  5.14  Female     No   Sun  Dinner     5
183       23.17  6.50    Male    Yes   Sun  Dinner     4
211       25.89  5.16    Male    Yes   Sat  Dinner     4
212       48.33  9.00    Male     No   Sat  Dinner     4

In [126]:
data = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie', 'Diana'],
    'Age': [25, 30, 35, 28],
    'City': ['New York', 'London', 'Tokyo', 'Paris'],
    'Salary': [50000, 60000, 70000, 55000]
})

In [127]:
df1= data

In [128]:
df1.isnull()

    Name    Age   City  Salary
0  False  False  False   False
1  False  False  False   False
2  False  False  False   False
3  False  False  False   False

In [129]:
df.isna()

     total_bill    tip    sex  smoker    day   time   size
0         False  False  False   False  False  False  False
1         False  False  False   False  False  False  False
2         False  False  False   False  False  False  False
3         False  False  False   False  False  False  False
4         False  False  False   False  False  False  False
..          ...    ...    ...     ...    ...    ...    ...
239       False  False  False   False  False  False  False
240       False  False  False   False  False  False  False
241       False  False  False   False  False  False  False
242       False  False  False   False  False  False  False
243       False  False  False   False  False  False  False

[244 rows x 7 columns]

In [130]:
df.isna().sum()

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64

In [131]:
df1.isna().any()

Name      False
Age       False
City      False
Salary    False
dtype: bool

In [132]:
df.isna().any().any()

np.False_

In [133]:
df.dropna(subset=['tip'])

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [134]:
df.dropna(how='all')

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [135]:
df.dropna(thresh=2)

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [136]:


data = {
    "student_id": [
        "STU001", "STU002", "STU003", "STU004", "STU005",
        "STU006", "STU007", "STU008", "STU009", "STU010",
        "STU011", "STU012", "STU013", "STU014", "STU015",
        "STU016", "STU017", "STU018", "STU019", "STU005"
    ],

    "name": [
        "Rahim", "Karim", "Mishu", "Nadia", "Sadia",
        "Tanvir", "Rafi", "Rima", "Ayesha", "Fahim",
        "Sakib", "Nusrat", "Arif", "Mim", "Hasan",
        "Jannat", "Rifat", "Tania", "Shuvo", "Sadia"
    ],

    "gender": [
        "Male", "Male", "male", "Female", "female",
        "M", "Male", "F", "Female", None,
        "Male", "Female", "male", "F", "Male",
        "Female", "M", "female", "Male", "female"
    ],

    "age": [
        20, 22, 21, 19, 23,
        24, 18, 20, 21, None,
        25, 22, 120, 19, 23,
        21, 24, 20, 22, 23
    ],

    "city": [
        "Dhaka", "Chittagong", " dhaka ", "Rajshahi", "Sylhet",
        "Khulna", "CHITTAGONG", "Barishal", "Rangpur", None,
        "Cumilla", "Dhaka", "Rajshahi", "sylhet", "Khulna",
        "Dhaka", "Chittagong", "barishal", "Rangpur", "Sylhet"
    ],

    "department": [
        "CSE", "EEE", "ete", "BBA", "Physics",
        "CSE", "EEE", "Civil", "Mechanical", "BBA",
        "Physics", "CSE", "EEE", "ETE", None,
        "Civil", "Mechanical", "BBA", "Physics", "EEE"
    ],

    "study_hours": [
        12, 18, 15, 8, 20,
        25, 10, 14, 16, None,
        30, 22, 95, 9, 13,
        7, 19, 11, 24, 20
    ],

    "attendance": [
        85, 90, 78, 65, 88,
        92, 55, 72, 80, 60,
        95, 89, 75, -10, 70,
        50, 82, 68, 91, 88
    ],

    "assignment_score": [
        80, 85, 75, 60, 90,
        88, 50, 70, 78, None,
        95, 86, 72, 65, 68,
        45, 82, 66, 89, 90
    ],

    "quiz_score": [
        70, 82, 68, 55, 88,
        91, 45, 63, 72, 58,
        96, 80, 67, 60, 62,
        42, 79, 64, 85, 88
    ],

    "final_score": [
        78, 88, 74, 62, 92,
        90, 52, 69, 76, 59,
        94, 85, 71, 64, 150,
        43, 81, 65, 87, 92
    ],

    "part_time_job": [
        "No", "Yes", "No", "yes", "No",
        "Yes", "No", "no", "Yes", None,
        "No", "Yes", "No", "No", "yes",
        "No", "Yes", "No", "No", "No"
    ],

    "internet_access": [
        "Yes", "Yes", "Yes", "No", "Yes",
        "Yes", "No", "Yes", "Yes", None,
        "Yes", "Yes", "No", "Yes", "Yes",
        "No", "Yes", "Yes", "Yes", "Yes"
    ],

    "learning_platform": [
        "Coursera", "YouTube", "Kaggle", "Google Classroom", "Udemy",
        "edX", "YouTube", "Coursera", "Kaggle", None,
        "Udemy", "Coursera", "YouTube", "Google Classroom", "edX",
        "YouTube", "Kaggle", "Coursera", "Udemy", "Udemy"
    ],

    "satisfaction": [
        4, 5, 3, 3, 5,
        4, 2, 3, 4, None,
        5, 4, 3, 2, 4,
        1, 4, 3, 5, 5
    ],

    "enrollment_date": [
        "2024-01-15", "2024-02-10", "2024-03-05", "2024-01-20", "2024-04-12",
        "2024-05-18", "2024-02-25", "2024-06-10", "2024-07-01", "2024-03-22",
        "2024-08-15", "2024-09-05", "2024-10-12", "2024-11-20", "2024-12-01",
        "2025-01-10", "2025-02-14", "2025-03-18", "2025-04-25", "2024-04-12"
    ]
}

df = pd.DataFrame(data)

df

,student_id,name,gender,age,city,department,study_hours,attendance,assignment_score,quiz_score,final_score,part_time_job,internet_access,learning_platform,satisfaction,enrollment_date
0,STU001,Rahim,Male,20.0,Dhaka,CSE,12.0,85,80.0,70,78,No,Yes,Coursera,4.0,2024-01-15
1,STU002,Karim,Male,22.0,Chittagong,EEE,18.0,90,85.0,82,88,Yes,Yes,YouTube,5.0,2024-02-10
2,STU003,Mishu,male,21.0,dhaka,ete,15.0,78,75.0,68,74,No,Yes,Kaggle,3.0,2024-03-05
3,STU004,Nadia,Female,19.0,Rajshahi,BBA,8.0,65,60.0,55,62,yes,No,Google Classroom,3.0,2024-01-20
4,STU005,Sadia,female,23.0,Sylhet,Physics,20.0,88,90.0,88,92,No,Yes,Udemy,5.0,2024-04-12
5,STU006,Tanvir,M,24.0,Khulna,CSE,25.0,92,88.0,91,90,Yes,Yes,edX,4.0,2024-05-18
6,STU007,Rafi,Male,18.0,CHITTAGONG,EEE,10.0,55,50.0,45,52,No,No,YouTube,2.0,2024-02-25
7,STU008,Rima,F,20.0,Barishal,Civil,14.0,72,70.0,63,69,no,Yes,Coursera,3.0,2024-06-10
8,STU009,Ayesha,Female,21.0,Rangpur,Mechanical,16.0,80,78.0,72,76,Yes,Yes,Kaggle,4.0,2024-07-01
9,STU010,Fahim,None,NaN,None,BBA,NaN,60,NaN,58,59,None,None,None,NaN,2024-03-22
10,STU011,Sakib,Male,25.0,Cumilla,Physics,30.0,95,95.0,96,94,No,Yes,Udemy,5.0,2024-08-15
11,STU012,Nusrat,Female,22.0,Dhaka,CSE,22.0,89,86.0,80,85,Yes,Yes,Coursera,4.0,2024-09-05
12,STU013,Arif,male,120.0,Rajshahi,EEE,95.0,75,72.0,67,71,No,No,YouTube,3.0,2024-10-12
13,STU014,Mim,F,19.0,sylhet,ETE,9.0,-10,65.0,60,64,No,Yes,Google Classroom,2.0,2024-11-20
14,STU015,Hasan,Male,23.0,Khulna,None,13.0,70,68.0,62,150,yes,Yes,edX,4.0,2024-12-01
15,STU016,Jannat,Female,21.0,Dhaka,Civil,7.0,50,45.0,42,43,No,No,YouTube,1.0,2025-01-10
16,STU017,Rifat,M,24.0,Chittagong,Mechanical,19.0,82,82.0,79,81,Yes,Yes,Kaggle,4.0,2025-02-14
17,STU018,Tania,female,20.0,barishal,BBA,11.0,68,66.0,64,65,No,Yes,Coursera,3.0,2025-03-18
18,STU019,Shuvo,Male,22.0,Rangpur,Physics,24.0,91,89.0,85,87,No,Yes,Udemy,5.0,2025-04-25
19,STU005,Sadia,female,23.0,Sylhet,EEE,20.0,88,90.0,88,92,No,Yes,Udemy,5.0,2024-04-12

In [137]:
df.isna().sum()

student_id           0
name                 0
gender               1
age                  1
city                 1
department           1
study_hours          1
attendance           0
assignment_score     1
quiz_score           0
final_score          0
part_time_job        1
internet_access      1
learning_platform    1
satisfaction         1
enrollment_date      0
dtype: int64

In [138]:
df.isna().any()

student_id           False
name                 False
gender                True
age                   True
city                  True
department            True
study_hours           True
attendance           False
assignment_score      True
quiz_score           False
final_score          False
part_time_job         True
internet_access       True
learning_platform     True
satisfaction          True
enrollment_date      False
dtype: bool

In [139]:
df.dropna(subset='age')

,student_id,name,gender,age,city,department,study_hours,attendance,assignment_score,quiz_score,final_score,part_time_job,internet_access,learning_platform,satisfaction,enrollment_date
0,STU001,Rahim,Male,20.0,Dhaka,CSE,12.0,85,80.0,70,78,No,Yes,Coursera,4.0,2024-01-15
1,STU002,Karim,Male,22.0,Chittagong,EEE,18.0,90,85.0,82,88,Yes,Yes,YouTube,5.0,2024-02-10
2,STU003,Mishu,male,21.0,dhaka,ete,15.0,78,75.0,68,74,No,Yes,Kaggle,3.0,2024-03-05
3,STU004,Nadia,Female,19.0,Rajshahi,BBA,8.0,65,60.0,55,62,yes,No,Google Classroom,3.0,2024-01-20
4,STU005,Sadia,female,23.0,Sylhet,Physics,20.0,88,90.0,88,92,No,Yes,Udemy,5.0,2024-04-12
5,STU006,Tanvir,M,24.0,Khulna,CSE,25.0,92,88.0,91,90,Yes,Yes,edX,4.0,2024-05-18
6,STU007,Rafi,Male,18.0,CHITTAGONG,EEE,10.0,55,50.0,45,52,No,No,YouTube,2.0,2024-02-25
7,STU008,Rima,F,20.0,Barishal,Civil,14.0,72,70.0,63,69,no,Yes,Coursera,3.0,2024-06-10
8,STU009,Ayesha,Female,21.0,Rangpur,Mechanical,16.0,80,78.0,72,76,Yes,Yes,Kaggle,4.0,2024-07-01
10,STU011,Sakib,Male,25.0,Cumilla,Physics,30.0,95,95.0,96,94,No,Yes,Udemy,5.0,2024-08-15
11,STU012,Nusrat,Female,22.0,Dhaka,CSE,22.0,89,86.0,80,85,Yes,Yes,Coursera,4.0,2024-09-05
12,STU013,Arif,male,120.0,Rajshahi,EEE,95.0,75,72.0,67,71,No,No,YouTube,3.0,2024-10-12
13,STU014,Mim,F,19.0,sylhet,ETE,9.0,-10,65.0,60,64,No,Yes,Google Classroom,2.0,2024-11-20
14,STU015,Hasan,Male,23.0,Khulna,None,13.0,70,68.0,62,150,yes,Yes,edX,4.0,2024-12-01
15,STU016,Jannat,Female,21.0,Dhaka,Civil,7.0,50,45.0,42,43,No,No,YouTube,1.0,2025-01-10
16,STU017,Rifat,M,24.0,Chittagong,Mechanical,19.0,82,82.0,79,81,Yes,Yes,Kaggle,4.0,2025-02-14
17,STU018,Tania,female,20.0,barishal,BBA,11.0,68,66.0,64,65,No,Yes,Coursera,3.0,2025-03-18
18,STU019,Shuvo,Male,22.0,Rangpur,Physics,24.0,91,89.0,85,87,No,Yes,Udemy,5.0,2025-04-25
19,STU005,Sadia,female,23.0,Sylhet,EEE,20.0,88,90.0,88,92,No,Yes,Udemy,5.0,2024-04-12

In [140]:
df.dropna(thresh=2)

,student_id,name,gender,age,city,department,study_hours,attendance,assignment_score,quiz_score,final_score,part_time_job,internet_access,learning_platform,satisfaction,enrollment_date
0,STU001,Rahim,Male,20.0,Dhaka,CSE,12.0,85,80.0,70,78,No,Yes,Coursera,4.0,2024-01-15
1,STU002,Karim,Male,22.0,Chittagong,EEE,18.0,90,85.0,82,88,Yes,Yes,YouTube,5.0,2024-02-10
2,STU003,Mishu,male,21.0,dhaka,ete,15.0,78,75.0,68,74,No,Yes,Kaggle,3.0,2024-03-05
3,STU004,Nadia,Female,19.0,Rajshahi,BBA,8.0,65,60.0,55,62,yes,No,Google Classroom,3.0,2024-01-20
4,STU005,Sadia,female,23.0,Sylhet,Physics,20.0,88,90.0,88,92,No,Yes,Udemy,5.0,2024-04-12
5,STU006,Tanvir,M,24.0,Khulna,CSE,25.0,92,88.0,91,90,Yes,Yes,edX,4.0,2024-05-18
6,STU007,Rafi,Male,18.0,CHITTAGONG,EEE,10.0,55,50.0,45,52,No,No,YouTube,2.0,2024-02-25
7,STU008,Rima,F,20.0,Barishal,Civil,14.0,72,70.0,63,69,no,Yes,Coursera,3.0,2024-06-10
8,STU009,Ayesha,Female,21.0,Rangpur,Mechanical,16.0,80,78.0,72,76,Yes,Yes,Kaggle,4.0,2024-07-01
9,STU010,Fahim,None,NaN,None,BBA,NaN,60,NaN,58,59,None,None,None,NaN,2024-03-22
10,STU011,Sakib,Male,25.0,Cumilla,Physics,30.0,95,95.0,96,94,No,Yes,Udemy,5.0,2024-08-15
11,STU012,Nusrat,Female,22.0,Dhaka,CSE,22.0,89,86.0,80,85,Yes,Yes,Coursera,4.0,2024-09-05
12,STU013,Arif,male,120.0,Rajshahi,EEE,95.0,75,72.0,67,71,No,No,YouTube,3.0,2024-10-12
13,STU014,Mim,F,19.0,sylhet,ETE,9.0,-10,65.0,60,64,No,Yes,Google Classroom,2.0,2024-11-20
14,STU015,Hasan,Male,23.0,Khulna,None,13.0,70,68.0,62,150,yes,Yes,edX,4.0,2024-12-01
15,STU016,Jannat,Female,21.0,Dhaka,Civil,7.0,50,45.0,42,43,No,No,YouTube,1.0,2025-01-10
16,STU017,Rifat,M,24.0,Chittagong,Mechanical,19.0,82,82.0,79,81,Yes,Yes,Kaggle,4.0,2025-02-14
17,STU018,Tania,female,20.0,barishal,BBA,11.0,68,66.0,64,65,No,Yes,Coursera,3.0,2025-03-18
18,STU019,Shuvo,Male,22.0,Rangpur,Physics,24.0,91,89.0,85,87,No,Yes,Udemy,5.0,2025-04-25
19,STU005,Sadia,female,23.0,Sylhet,EEE,20.0,88,90.0,88,92,No,Yes,Udemy,5.0,2024-04-12

In [141]:
df.shape

(20, 16)

In [142]:
df['age'].fillna(df['age'].mean())

0      20.000000
1      22.000000
2      21.000000
3      19.000000
4      23.000000
5      24.000000
6      18.000000
7      20.000000
8      21.000000
9      26.684211
10     25.000000
11     22.000000
12    120.000000
13     19.000000
14     23.000000
15     21.000000
16     24.000000
17     20.000000
18     22.000000
19     23.000000
Name: age, dtype: float64

In [143]:
df.fillna(method='ffill').head(3)

C:\Users\PL\AppData\Local\Temp\ipykernel_18924\1892254875.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill').head(3)

,student_id,name,gender,age,city,department,study_hours,attendance,assignment_score,quiz_score,final_score,part_time_job,internet_access,learning_platform,satisfaction,enrollment_date
0,STU001,Rahim,Male,20.0,Dhaka,CSE,12.0,85,80.0,70,78,No,Yes,Coursera,4.0,2024-01-15
1,STU002,Karim,Male,22.0,Chittagong,EEE,18.0,90,85.0,82,88,Yes,Yes,YouTube,5.0,2024-02-10
2,STU003,Mishu,male,21.0,dhaka,ete,15.0,78,75.0,68,74,No,Yes,Kaggle,3.0,2024-03-05

In [144]:
df.duplicated().sum()

np.int64(0)

In [145]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   student_id         20 non-null     object
 1   name               20 non-null     object
 2   gender             19 non-null     object
 3   age                19 non-null     float64
 4   city               19 non-null     object
 5   department         19 non-null     object
 6   study_hours        19 non-null     float64
 7   attendance         20 non-null     int64
 8   assignment_score   19 non-null     float64
 9   quiz_score         20 non-null     int64
 10  final_score        20 non-null     int64
 11  part_time_job      19 non-null     object
 12  internet_access    19 non-null     object
 13  learning_platform  19 non-null     object
 14  satisfaction       19 non-null     float64
 15  enrollment_date    20 non-null     object
dtypes: float64(4), int64(3), object(9)
memory usage: 2.6+ KB

In [146]:
df.dtypes.value_counts()

object     9
float64    4
int64      3
Name: count, dtype: int64

In [147]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   student_id         20 non-null     object
 1   name               20 non-null     object
 2   gender             19 non-null     object
 3   age                19 non-null     float64
 4   city               19 non-null     object
 5   department         19 non-null     object
 6   study_hours        19 non-null     float64
 7   attendance         20 non-null     int64
 8   assignment_score   19 non-null     float64
 9   quiz_score         20 non-null     int64
 10  final_score        20 non-null     int64
 11  part_time_job      19 non-null     object
 12  internet_access    19 non-null     object
 13  learning_platform  19 non-null     object
 14  satisfaction       19 non-null     float64
 15  enrollment_date    20 non-null     object
dtypes: float64(4), int64(3), object(9)
memory usage: 2.6+ KB

In [148]:
df.dropna(inplace=True)

In [149]:
df['city'] = df['city'].astype('category')

In [150]:
df.head()

,student_id,name,gender,age,city,department,study_hours,attendance,assignment_score,quiz_score,final_score,part_time_job,internet_access,learning_platform,satisfaction,enrollment_date
0,STU001,Rahim,Male,20.0,Dhaka,CSE,12.0,85,80.0,70,78,No,Yes,Coursera,4.0,2024-01-15
1,STU002,Karim,Male,22.0,Chittagong,EEE,18.0,90,85.0,82,88,Yes,Yes,YouTube,5.0,2024-02-10
2,STU003,Mishu,male,21.0,dhaka,ete,15.0,78,75.0,68,74,No,Yes,Kaggle,3.0,2024-03-05
3,STU004,Nadia,Female,19.0,Rajshahi,BBA,8.0,65,60.0,55,62,yes,No,Google Classroom,3.0,2024-01-20
4,STU005,Sadia,female,23.0,Sylhet,Physics,20.0,88,90.0,88,92,No,Yes,Udemy,5.0,2024-04-12

In [163]:
df.index = df.index.str.replace('STU', '', regex=False).astype(int)

In [164]:
df.head()

,name,gender,age,city,department,study_hours,attendance,assignment_score,quiz_score,final_score,part_time_job,internet_access,learning_platform,satisfaction,enrollment_date
student_id,,,,,,,,,,,,,,,
1,Rahim,Male,20.0,Dhaka,CSE,12.0,85,80.0,70,78,No,Yes,Coursera,4.0,15-01-2024
2,Karim,Male,22.0,Chittagong,EEE,18.0,90,85.0,82,88,Yes,Yes,YouTube,5.0,10-02-2024
3,Mishu,male,21.0,dhaka,ete,15.0,78,75.0,68,74,No,Yes,Kaggle,3.0,05-03-2024
4,Nadia,Female,19.0,Rajshahi,BBA,8.0,65,60.0,55,62,yes,No,Google Classroom,3.0,20-01-2024
5,Sadia,female,23.0,Sylhet,Physics,20.0,88,90.0,88,92,No,Yes,Udemy,5.0,12-04-2024

In [153]:
df.set_index('student_id',inplace=True)

In [154]:
df['name']= df['name'].astype(str)

In [155]:
df['enrollment_date'] = pd.to_datetime(
    df['enrollment_date'],
    dayfirst=True,       # ensures day comes first
    errors='coerce'      # invalid parsing becomes NaT
)

C:\Users\PL\AppData\Local\Temp\ipykernel_18924\3526178255.py:1: UserWarning: Parsing dates in %Y-%m-%d format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  df['enrollment_date'] = pd.to_datetime(

In [156]:
df.head()

,name,gender,age,city,department,study_hours,attendance,assignment_score,quiz_score,final_score,part_time_job,internet_access,learning_platform,satisfaction,enrollment_date
student_id,,,,,,,,,,,,,,,
STU1,Rahim,Male,20.0,Dhaka,CSE,12.0,85,80.0,70,78,No,Yes,Coursera,4.0,2024-01-15
STU2,Karim,Male,22.0,Chittagong,EEE,18.0,90,85.0,82,88,Yes,Yes,YouTube,5.0,2024-02-10
STU3,Mishu,male,21.0,dhaka,ete,15.0,78,75.0,68,74,No,Yes,Kaggle,3.0,2024-03-05
STU4,Nadia,Female,19.0,Rajshahi,BBA,8.0,65,60.0,55,62,yes,No,Google Classroom,3.0,2024-01-20
STU5,Sadia,female,23.0,Sylhet,Physics,20.0,88,90.0,88,92,No,Yes,Udemy,5.0,2024-04-12

In [157]:
df['enrollment_date'] = pd.to_datetime(df['enrollment_date'], errors='coerce')

df['enrollment_date'] = df['enrollment_date'].dt.strftime('%d-%m-%Y')

In [158]:
df['age'] = pd.to_numeric(df['age'], errors='coerce')
df['age'] = pd.to_numeric(df['age'], errors='ignore')

C:\Users\PL\AppData\Local\Temp\ipykernel_18924\785872427.py:2: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df['age'] = pd.to_numeric(df['age'], errors='ignore')

In [165]:
df.head()

,name,gender,age,city,department,study_hours,attendance,assignment_score,quiz_score,final_score,part_time_job,internet_access,learning_platform,satisfaction,enrollment_date
student_id,,,,,,,,,,,,,,,
1,Rahim,Male,20.0,Dhaka,CSE,12.0,85,80.0,70,78,No,Yes,Coursera,4.0,15-01-2024
2,Karim,Male,22.0,Chittagong,EEE,18.0,90,85.0,82,88,Yes,Yes,YouTube,5.0,10-02-2024
3,Mishu,male,21.0,dhaka,ete,15.0,78,75.0,68,74,No,Yes,Kaggle,3.0,05-03-2024
4,Nadia,Female,19.0,Rajshahi,BBA,8.0,65,60.0,55,62,yes,No,Google Classroom,3.0,20-01-2024
5,Sadia,female,23.0,Sylhet,Physics,20.0,88,90.0,88,92,No,Yes,Udemy,5.0,12-04-2024

In [168]:
df.drop(df.index[19:])

,name,gender,age,city,department,study_hours,attendance,assignment_score,quiz_score,final_score,part_time_job,internet_access,learning_platform,satisfaction,enrollment_date
student_id,,,,,,,,,,,,,,,
1,Rahim,Male,20.0,Dhaka,CSE,12.0,85,80.0,70,78,No,Yes,Coursera,4.0,15-01-2024
2,Karim,Male,22.0,Chittagong,EEE,18.0,90,85.0,82,88,Yes,Yes,YouTube,5.0,10-02-2024
3,Mishu,male,21.0,dhaka,ete,15.0,78,75.0,68,74,No,Yes,Kaggle,3.0,05-03-2024
4,Nadia,Female,19.0,Rajshahi,BBA,8.0,65,60.0,55,62,yes,No,Google Classroom,3.0,20-01-2024
5,Sadia,female,23.0,Sylhet,Physics,20.0,88,90.0,88,92,No,Yes,Udemy,5.0,12-04-2024
6,Tanvir,M,24.0,Khulna,CSE,25.0,92,88.0,91,90,Yes,Yes,edX,4.0,18-05-2024
7,Rafi,Male,18.0,CHITTAGONG,EEE,10.0,55,50.0,45,52,No,No,YouTube,2.0,25-02-2024
8,Rima,F,20.0,Barishal,Civil,14.0,72,70.0,63,69,no,Yes,Coursera,3.0,10-06-2024
9,Ayesha,Female,21.0,Rangpur,Mechanical,16.0,80,78.0,72,76,Yes,Yes,Kaggle,4.0,01-07-2024
11,Sakib,Male,25.0,Cumilla,Physics,30.0,95,95.0,96,94,No,Yes,Udemy,5.0,15-08-2024
12,Nusrat,Female,22.0,Dhaka,CSE,22.0,89,86.0,80,85,Yes,Yes,Coursera,4.0,05-09-2024
13,Arif,male,120.0,Rajshahi,EEE,95.0,75,72.0,67,71,No,No,YouTube,3.0,12-10-2024
14,Mim,F,19.0,sylhet,ETE,9.0,-10,65.0,60,64,No,Yes,Google Classroom,2.0,20-11-2024
16,Jannat,Female,21.0,Dhaka,Civil,7.0,50,45.0,42,43,No,No,YouTube,1.0,10-01-2025
17,Rifat,M,24.0,Chittagong,Mechanical,19.0,82,82.0,79,81,Yes,Yes,Kaggle,4.0,14-02-2025
18,Tania,female,20.0,barishal,BBA,11.0,68,66.0,64,65,No,Yes,Coursera,3.0,18-03-2025
19,Shuvo,Male,22.0,Rangpur,Physics,24.0,91,89.0,85,87,No,Yes,Udemy,5.0,25-04-2025
5,Sadia,female,23.0,Sylhet,EEE,20.0,88,90.0,88,92,No,Yes,Udemy,5.0,12-04-2024

In [167]:
df.drop_duplicates(inplace=True)

In [170]:
# show duplicate index rows
print(df[df.index.duplicated(keep=False)])

# drop duplicate index, keeping first
df = df[~df.index.duplicated(keep='first')]

             name  gender   age    city department  study_hours  attendance  \
student_id
5           Sadia  female  23.0  Sylhet    Physics         20.0          88
5           Sadia  female  23.0  Sylhet        EEE         20.0          88

            assignment_score  quiz_score  final_score part_time_job  \
student_id
5                       90.0          88           92            No
5                       90.0          88           92            No

           internet_access learning_platform  satisfaction enrollment_date
student_id
5                      Yes             Udemy           5.0      12-04-2024
5                      Yes             Udemy           5.0      12-04-2024

In [172]:
df

,name,gender,age,city,department,study_hours,attendance,assignment_score,quiz_score,final_score,part_time_job,internet_access,learning_platform,satisfaction,enrollment_date
student_id,,,,,,,,,,,,,,,
1,Rahim,Male,20.0,Dhaka,CSE,12.0,85,80.0,70,78,No,Yes,Coursera,4.0,15-01-2024
2,Karim,Male,22.0,Chittagong,EEE,18.0,90,85.0,82,88,Yes,Yes,YouTube,5.0,10-02-2024
3,Mishu,male,21.0,dhaka,ete,15.0,78,75.0,68,74,No,Yes,Kaggle,3.0,05-03-2024
4,Nadia,Female,19.0,Rajshahi,BBA,8.0,65,60.0,55,62,yes,No,Google Classroom,3.0,20-01-2024
5,Sadia,female,23.0,Sylhet,Physics,20.0,88,90.0,88,92,No,Yes,Udemy,5.0,12-04-2024
6,Tanvir,M,24.0,Khulna,CSE,25.0,92,88.0,91,90,Yes,Yes,edX,4.0,18-05-2024
7,Rafi,Male,18.0,CHITTAGONG,EEE,10.0,55,50.0,45,52,No,No,YouTube,2.0,25-02-2024
8,Rima,F,20.0,Barishal,Civil,14.0,72,70.0,63,69,no,Yes,Coursera,3.0,10-06-2024
9,Ayesha,Female,21.0,Rangpur,Mechanical,16.0,80,78.0,72,76,Yes,Yes,Kaggle,4.0,01-07-2024
11,Sakib,Male,25.0,Cumilla,Physics,30.0,95,95.0,96,94,No,Yes,Udemy,5.0,15-08-2024
12,Nusrat,Female,22.0,Dhaka,CSE,22.0,89,86.0,80,85,Yes,Yes,Coursera,4.0,05-09-2024
13,Arif,male,120.0,Rajshahi,EEE,95.0,75,72.0,67,71,No,No,YouTube,3.0,12-10-2024
14,Mim,F,19.0,sylhet,ETE,9.0,-10,65.0,60,64,No,Yes,Google Classroom,2.0,20-11-2024
16,Jannat,Female,21.0,Dhaka,Civil,7.0,50,45.0,42,43,No,No,YouTube,1.0,10-01-2025
17,Rifat,M,24.0,Chittagong,Mechanical,19.0,82,82.0,79,81,Yes,Yes,Kaggle,4.0,14-02-2025
18,Tania,female,20.0,barishal,BBA,11.0,68,66.0,64,65,No,Yes,Coursera,3.0,18-03-2025
19,Shuvo,Male,22.0,Rangpur,Physics,24.0,91,89.0,85,87,No,Yes,Udemy,5.0,25-04-2025

In [175]:
df.duplicated(subset=['name']).sum()

np.int64(0)

In [176]:
df['name'].str.upper()

student_id
1      RAHIM
2      KARIM
3      MISHU
4      NADIA
5      SADIA
6     TANVIR
7       RAFI
8       RIMA
9     AYESHA
11     SAKIB
12    NUSRAT
13      ARIF
14       MIM
16    JANNAT
17     RIFAT
18     TANIA
19     SHUVO
Name: name, dtype: object

In [178]:
df['name'].str.capitalize()

student_id
1      Rahim
2      Karim
3      Mishu
4      Nadia
5      Sadia
6     Tanvir
7       Rafi
8       Rima
9     Ayesha
11     Sakib
12    Nusrat
13      Arif
14       Mim
16    Jannat
17     Rifat
18     Tania
19     Shuvo
Name: name, dtype: object

In [180]:
df['name'].str.strip()
df['name'].str.lstrip()
df['name'].str.rstrip()

student_id
1      Rahim
2      Karim
3      Mishu
4      Nadia
5      Sadia
6     Tanvir
7       Rafi
8       Rima
9     Ayesha
11     Sakib
12    Nusrat
13      Arif
14       Mim
16    Jannat
17     Rifat
18     Tania
19     Shuvo
Name: name, dtype: object

In [183]:
df['age'].quantile(0.25)

np.float64(20.0)

In [186]:
print(df['age'].skew())

4.078166387758953

In [187]:
print(df['age'].kurtosis())

16.737942130726065

In [194]:
normalize =df['city'].value_counts(normalize=True).reset_index().round(2)

In [197]:
normalize['proportion']*100

0     18.0
1     12.0
2     12.0
3     12.0
4      6.0
5      6.0
6      6.0
7      6.0
8      6.0
9      6.0
10     6.0
11     6.0
Name: proportion, dtype: float64

In [198]:
df['city'].nunique()

12

In [201]:
df.head()

,name,gender,age,city,department,study_hours,attendance,assignment_score,quiz_score,final_score,part_time_job,internet_access,learning_platform,satisfaction,enrollment_date
student_id,,,,,,,,,,,,,,,
1,Rahim,Male,20.0,Dhaka,CSE,12.0,85,80.0,70,78,No,Yes,Coursera,4.0,15-01-2024
2,Karim,Male,22.0,Chittagong,EEE,18.0,90,85.0,82,88,Yes,Yes,YouTube,5.0,10-02-2024
3,Mishu,male,21.0,dhaka,ete,15.0,78,75.0,68,74,No,Yes,Kaggle,3.0,05-03-2024
4,Nadia,Female,19.0,Rajshahi,BBA,8.0,65,60.0,55,62,yes,No,Google Classroom,3.0,20-01-2024
5,Sadia,female,23.0,Sylhet,Physics,20.0,88,90.0,88,92,No,Yes,Udemy,5.0,12-04-2024

In [207]:
df[['quiz_score', 'final_score']].corr()

             quiz_score  final_score
quiz_score     1.000000     0.983596
final_score    0.983596     1.000000

In [209]:
df.groupby('city')['age'].agg(['mean','median'])

C:\Users\PL\AppData\Local\Temp\ipykernel_18924\3160632751.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('city')['age'].agg(['mean','median'])

            mean  median
city
 dhaka      21.0    21.0
Barishal    20.0    20.0
CHITTAGONG  18.0    18.0
Chittagong  23.0    23.0
Cumilla     25.0    25.0
Dhaka       21.0    21.0
Khulna      24.0    24.0
Rajshahi    69.5    69.5
Rangpur     21.5    21.5
Sylhet      23.0    23.0
barishal    20.0    20.0
sylhet      19.0    19.0

In [ ]:
# Multiple aggregations
agg_dict = {
    'age': ['mean', 'min', 'max'],
    }
result = df.groupby('city').agg(agg_dict)
print(result)

# Custom function
def range_func(x):
    return x.max() - x.min()

result = df.groupby('city')['age'].agg(range_func)
print(result)

             age
            mean   min    max
city
 dhaka      21.0  21.0   21.0
Barishal    20.0  20.0   20.0
CHITTAGONG  18.0  18.0   18.0
Chittagong  23.0  22.0   24.0
Cumilla     25.0  25.0   25.0
Dhaka       21.0  20.0   22.0
Khulna      24.0  24.0   24.0
Rajshahi    69.5  19.0  120.0
Rangpur     21.5  21.0   22.0
Sylhet      23.0  23.0   23.0
barishal    20.0  20.0   20.0
sylhet      19.0  19.0   19.0

C:\Users\PL\AppData\Local\Temp\ipykernel_18924\2551503339.py:5: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  result = df.groupby('city').agg(agg_dict)

KeyError: 'City'

In [214]:
df.columns.str.capitalize()

Index(['Name', 'Gender', 'Age', 'City', 'Department', 'Study_hours',
       'Attendance', 'Assignment_score', 'Quiz_score', 'Final_score',
       'Part_time_job', 'Internet_access', 'Learning_platform', 'Satisfaction',
       'Enrollment_date'],
      dtype='object')

In [215]:
df

,name,gender,age,city,department,study_hours,attendance,assignment_score,quiz_score,final_score,part_time_job,internet_access,learning_platform,satisfaction,enrollment_date
student_id,,,,,,,,,,,,,,,
1,Rahim,Male,20.0,Dhaka,CSE,12.0,85,80.0,70,78,No,Yes,Coursera,4.0,15-01-2024
2,Karim,Male,22.0,Chittagong,EEE,18.0,90,85.0,82,88,Yes,Yes,YouTube,5.0,10-02-2024
3,Mishu,male,21.0,dhaka,ete,15.0,78,75.0,68,74,No,Yes,Kaggle,3.0,05-03-2024
4,Nadia,Female,19.0,Rajshahi,BBA,8.0,65,60.0,55,62,yes,No,Google Classroom,3.0,20-01-2024
5,Sadia,female,23.0,Sylhet,Physics,20.0,88,90.0,88,92,No,Yes,Udemy,5.0,12-04-2024
6,Tanvir,M,24.0,Khulna,CSE,25.0,92,88.0,91,90,Yes,Yes,edX,4.0,18-05-2024
7,Rafi,Male,18.0,CHITTAGONG,EEE,10.0,55,50.0,45,52,No,No,YouTube,2.0,25-02-2024
8,Rima,F,20.0,Barishal,Civil,14.0,72,70.0,63,69,no,Yes,Coursera,3.0,10-06-2024
9,Ayesha,Female,21.0,Rangpur,Mechanical,16.0,80,78.0,72,76,Yes,Yes,Kaggle,4.0,01-07-2024
11,Sakib,Male,25.0,Cumilla,Physics,30.0,95,95.0,96,94,No,Yes,Udemy,5.0,15-08-2024
12,Nusrat,Female,22.0,Dhaka,CSE,22.0,89,86.0,80,85,Yes,Yes,Coursera,4.0,05-09-2024
13,Arif,male,120.0,Rajshahi,EEE,95.0,75,72.0,67,71,No,No,YouTube,3.0,12-10-2024
14,Mim,F,19.0,sylhet,ETE,9.0,-10,65.0,60,64,No,Yes,Google Classroom,2.0,20-11-2024
16,Jannat,Female,21.0,Dhaka,Civil,7.0,50,45.0,42,43,No,No,YouTube,1.0,10-01-2025
17,Rifat,M,24.0,Chittagong,Mechanical,19.0,82,82.0,79,81,Yes,Yes,Kaggle,4.0,14-02-2025
18,Tania,female,20.0,barishal,BBA,11.0,68,66.0,64,65,No,Yes,Coursera,3.0,18-03-2025
19,Shuvo,Male,22.0,Rangpur,Physics,24.0,91,89.0,85,87,No,Yes,Udemy,5.0,25-04-2025

In [221]:
pd.crosstab(df['city'], df['age'], margins=True , normalize=True).round(2)

age         18.0  19.0  20.0  21.0  22.0  23.0  24.0  25.0  120.0   All
city
 dhaka      0.00  0.00  0.00  0.06  0.00  0.00  0.00  0.00   0.00  0.06
Barishal    0.00  0.00  0.06  0.00  0.00  0.00  0.00  0.00   0.00  0.06
CHITTAGONG  0.06  0.00  0.00  0.00  0.00  0.00  0.00  0.00   0.00  0.06
Chittagong  0.00  0.00  0.00  0.00  0.06  0.00  0.06  0.00   0.00  0.12
Cumilla     0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.06   0.00  0.06
Dhaka       0.00  0.00  0.06  0.06  0.06  0.00  0.00  0.00   0.00  0.18
Khulna      0.00  0.00  0.00  0.00  0.00  0.00  0.06  0.00   0.00  0.06
Rajshahi    0.00  0.06  0.00  0.00  0.00  0.00  0.00  0.00   0.06  0.12
Rangpur     0.00  0.00  0.00  0.06  0.06  0.00  0.00  0.00   0.00  0.12
Sylhet      0.00  0.00  0.00  0.00  0.00  0.06  0.00  0.00   0.00  0.06
barishal    0.00  0.00  0.06  0.00  0.00  0.00  0.00  0.00   0.00  0.06
sylhet      0.00  0.06  0.00  0.00  0.00  0.00  0.00  0.00   0.00  0.06
All         0.06  0.12  0.18  0.18  0.18  0.06  0.12  0.06   0.06  1.00

In [218]:
pivot = df.pivot_table(
    values='final_score',
    index='city',
    aggfunc='mean',
    margins=True  # Add row/column totals
)

C:\Users\PL\AppData\Local\Temp\ipykernel_18924\421562065.py:1: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  pivot = df.pivot_table(

In [219]:
pivot

            final_score
city
 dhaka        74.000000
Barishal      69.000000
CHITTAGONG    52.000000
Chittagong    84.500000
Cumilla       94.000000
Dhaka         68.666667
Khulna        90.000000
Rajshahi      66.500000
Rangpur       81.500000
Sylhet        92.000000
barishal      65.000000
sylhet        64.000000
All           74.764706

In [ ]:
pd.date_range('2024-01-01', periods=10, freq='D')

DatetimeIndex(['2024-01-01', '2024-01-02', '2024-01-03', '2024-01-04',
               '2024-01-05', '2024-01-06', '2024-01-07', '2024-01-08',
               '2024-01-09', '2024-01-10'],
              dtype='datetime64[ns]', freq='D')

In [225]:
import pandas as pd
import numpy as np

sales_df = pd.DataFrame({
    'Date': pd.date_range('2024-01-01', periods=100, freq='D'),
    'Sales': np.random.randint(1000, 5000, 100)
})

sales_df = sales_df.set_index('Date')

sales_df.head()

            Sales
Date
2024-01-01   1618
2024-01-02   1351
2024-01-03   3262
2024-01-04   1888
2024-01-05   1307

In [226]:
sales_df.resample('M').sum()

C:\Users\PL\AppData\Local\Temp\ipykernel_18924\1755035507.py:1: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  sales_df.resample('M').sum()

            Sales
Date
2024-01-31  91506
2024-02-29  83266
2024-03-31  93247
2024-04-30  26212

In [228]:
df.select_dtypes(include=[np.number]).columns

Index(['age', 'study_hours', 'attendance', 'assignment_score', 'quiz_score',
       'final_score', 'satisfaction'],
      dtype='object')