In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [8]:
df = pd.read_excel('devision & district wise page24.xlsx')

In [9]:
df

,Column1,Column2,Column3,Column4,Column5,Column6,Column7,Column8,Column9,Column10,Column11,Column12
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Division,District,FY 2017-18,FY 2018-19,FY 2019-20,FY 2020-21,FY 2021-22,FY 2022-23,FY 2023-24,July,August,September
2,BARISAL,BARGUNA,46.4,47.6,50.3,64.5,52.6,57.9,62.5,3.9,5.0,8.1
3,NaN,BARISHAL,174.8,188.8,220.5,255.5,222.1,185.3,202.4,16.7,25.6,27.8
4,NaN,BHOLA,87.3,81.6,80.8,106.2,87.9,87.6,99.5,7.7,9.0,11.2
...,...,...,...,...,...,...,...,...,...,...,...,...
70,NaN,MOULVI BAZAR,359.7,361.7,379.4,469.8,498.9,579.2,568.4,44.1,41.6,49.2
71,NaN,SUNAMGANJ,190.2,214.1,223.4,292.9,282.6,323.9,322.9,24.1,28.0,30.2
72,NaN,SYLHET,905.6,942.3,1032.9,1372.7,1085.0,1244.1,1339.3,94.7,103.8,112.7
73,NaN,SYLHET Total,1682.6,1771.0,1899.2,2444.5,2149.5,2471.4,2543.2,186.7,202.4,221.9
74,Total,NaN,14981.9,16419.7,18205.1,24777.7,21031.7,21610.7,23912.2,1913.8,2224.2,2404.1

,Column1,Column2,Column3,Column4,Column5,Column6,Column7,Column8,Column9,Column10,Column11,Column12
1,Division,District,FY 2017-18,FY 2018-19,FY 2019-20,FY 2020-21,FY 2021-22,FY 2022-23,FY 2023-24,July,August,September
2,BARISAL,BARGUNA,46.4,47.6,50.3,64.5,52.6,57.9,62.5,3.9,5.0,8.1
3,NaN,BARISHAL,174.8,188.8,220.5,255.5,222.1,185.3,202.4,16.7,25.6,27.8
4,NaN,BHOLA,87.3,81.6,80.8,106.2,87.9,87.6,99.5,7.7,9.0,11.2
5,NaN,JHALOKATI,37.3,44.2,39.7,52.7,40.4,43.9,55.5,4.1,5.6,7.2
...,...,...,...,...,...,...,...,...,...,...,...,...
70,NaN,MOULVI BAZAR,359.7,361.7,379.4,469.8,498.9,579.2,568.4,44.1,41.6,49.2
71,NaN,SUNAMGANJ,190.2,214.1,223.4,292.9,282.6,323.9,322.9,24.1,28.0,30.2
72,NaN,SYLHET,905.6,942.3,1032.9,1372.7,1085.0,1244.1,1339.3,94.7,103.8,112.7
73,NaN,SYLHET Total,1682.6,1771.0,1899.2,2444.5,2149.5,2471.4,2543.2,186.7,202.4,221.9
74,Total,NaN,14981.9,16419.7,18205.1,24777.7,21031.7,21610.7,23912.2,1913.8,2224.2,2404.1

In [11]:
df.columns=df.loc[1]

In [12]:
df

1,Division,District,FY 2017-18,FY 2018-19,FY 2019-20,FY 2020-21,FY 2021-22,FY 2022-23,FY 2023-24,July,August,September
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Division,District,FY 2017-18,FY 2018-19,FY 2019-20,FY 2020-21,FY 2021-22,FY 2022-23,FY 2023-24,July,August,September
2,BARISAL,BARGUNA,46.4,47.6,50.3,64.5,52.6,57.9,62.5,3.9,5.0,8.1
3,NaN,BARISHAL,174.8,188.8,220.5,255.5,222.1,185.3,202.4,16.7,25.6,27.8
4,NaN,BHOLA,87.3,81.6,80.8,106.2,87.9,87.6,99.5,7.7,9.0,11.2
...,...,...,...,...,...,...,...,...,...,...,...,...
70,NaN,MOULVI BAZAR,359.7,361.7,379.4,469.8,498.9,579.2,568.4,44.1,41.6,49.2
71,NaN,SUNAMGANJ,190.2,214.1,223.4,292.9,282.6,323.9,322.9,24.1,28.0,30.2
72,NaN,SYLHET,905.6,942.3,1032.9,1372.7,1085.0,1244.1,1339.3,94.7,103.8,112.7
73,NaN,SYLHET Total,1682.6,1771.0,1899.2,2444.5,2149.5,2471.4,2543.2,186.7,202.4,221.9
74,Total,NaN,14981.9,16419.7,18205.1,24777.7,21031.7,21610.7,23912.2,1913.8,2224.2,2404.1

In [20]:
df =df.drop(df.index[0:2])

In [21]:
df.shape

(73, 12)

In [22]:
df.columns.to_list()

['Division',
 'District',
 'FY 2017-18',
 'FY 2018-19',
 'FY 2019-20',
 'FY 2020-21',
 'FY 2021-22',
 'FY 2022-23',
 'FY 2023-24',
 'July',
 'August',
 'September']

In [23]:
df.dtypes

1
Division      object
District      object
FY 2017-18    object
FY 2018-19    object
FY 2019-20    object
FY 2020-21    object
FY 2021-22    object
FY 2022-23    object
FY 2023-24    object
July          object
August        object
September     object
dtype: object

In [24]:
df.head(5)

1,Division,District,FY 2017-18,FY 2018-19,FY 2019-20,FY 2020-21,FY 2021-22,FY 2022-23,FY 2023-24,July,August,September
2,BARISAL,BARGUNA,46.4,47.6,50.3,64.5,52.6,57.9,62.5,3.9,5.0,8.1
3,NaN,BARISHAL,174.8,188.8,220.5,255.5,222.1,185.3,202.4,16.7,25.6,27.8
4,NaN,BHOLA,87.3,81.6,80.8,106.2,87.9,87.6,99.5,7.7,9.0,11.2
5,NaN,JHALOKATI,37.3,44.2,39.7,52.7,40.4,43.9,55.5,4.1,5.6,7.2
6,NaN,PATUAKHALI,52.8,56.7,52.7,77.6,63.2,59.5,63.0,4.4,6.5,8.6

In [25]:
df.sample(5)

1,Division,District,FY 2017-18,FY 2018-19,FY 2019-20,FY 2020-21,FY 2021-22,FY 2022-23,FY 2023-24,July,August,September
52,NaN,CHAPAI NAWABGANJ,83.9,76.1,81.7,93.6,91.4,102.0,113.5,8.5,14.9,13.7
53,NaN,JOYPURHAT,61.2,34.0,31.5,41.5,47.5,46.4,36.6,2.1,2.7,4.7
47,NaN,MYMENSINGH,180.3,210.7,228.0,303.1,263.2,210.0,209.3,17.0,22.8,28.0
72,NaN,SYLHET,905.6,942.3,1032.9,1372.7,1085.0,1244.1,1339.3,94.7,103.8,112.7
24,NaN,GOPALGANJ,62.3,76.1,77.1,115.6,93.2,86.3,105.3,8.8,11.6,14.9

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 73 entries, 2 to 74
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Division    9 non-null      object
 1   District    72 non-null     object
 2   FY 2017-18  73 non-null     object
 3   FY 2018-19  73 non-null     object
 4   FY 2019-20  73 non-null     object
 5   FY 2020-21  73 non-null     object
 6   FY 2021-22  73 non-null     object
 7   FY 2022-23  73 non-null     object
 8   FY 2023-24  73 non-null     object
 9   July        73 non-null     object
 10  August      73 non-null     object
 11  September   73 non-null     object
dtypes: object(12)
memory usage: 7.0+ KB

In [30]:
df.describe(include=object)

1,division,district,fy 2017-18,fy 2018-19,fy 2019-20,fy 2020-21,fy 2021-22,fy 2022-23,fy 2023-24,july,august,september
count,9,72,73,73,73,73,73,73,73,73,73,73
unique,9,72,73,70,72,73,73,73,73,66,69,68
top,BARISAL,BARGUNA,46.4,47.6,16.6,64.5,52.6,57.9,62.5,3.9,25.6,7.2
freq,1,1,1,2,2,1,1,1,1,2,2,2

In [28]:
df.rename(columns=str.lower,inplace=True)

In [29]:
df

1,division,district,fy 2017-18,fy 2018-19,fy 2019-20,fy 2020-21,fy 2021-22,fy 2022-23,fy 2023-24,july,august,september
2,BARISAL,BARGUNA,46.4,47.6,50.3,64.5,52.6,57.9,62.5,3.9,5.0,8.1
3,NaN,BARISHAL,174.8,188.8,220.5,255.5,222.1,185.3,202.4,16.7,25.6,27.8
4,NaN,BHOLA,87.3,81.6,80.8,106.2,87.9,87.6,99.5,7.7,9.0,11.2
5,NaN,JHALOKATI,37.3,44.2,39.7,52.7,40.4,43.9,55.5,4.1,5.6,7.2
6,NaN,PATUAKHALI,52.8,56.7,52.7,77.6,63.2,59.5,63.0,4.4,6.5,8.6
...,...,...,...,...,...,...,...,...,...,...,...,...
70,NaN,MOULVI BAZAR,359.7,361.7,379.4,469.8,498.9,579.2,568.4,44.1,41.6,49.2
71,NaN,SUNAMGANJ,190.2,214.1,223.4,292.9,282.6,323.9,322.9,24.1,28.0,30.2
72,NaN,SYLHET,905.6,942.3,1032.9,1372.7,1085.0,1244.1,1339.3,94.7,103.8,112.7
73,NaN,SYLHET Total,1682.6,1771.0,1899.2,2444.5,2149.5,2471.4,2543.2,186.7,202.4,221.9
74,Total,NaN,14981.9,16419.7,18205.1,24777.7,21031.7,21610.7,23912.2,1913.8,2224.2,2404.1

Index([], dtype='object', name=1)

In [35]:
df_to_numeric = df.iloc[:,2:]

In [36]:
df_to_numeric= df_to_numeric.columns

In [38]:
df[df_to_numeric] = df[df_to_numeric].astype('float')

In [40]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 73 entries, 2 to 74
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   division    9 non-null      object
 1   district    72 non-null     object
 2   fy 2017-18  73 non-null     float64
 3   fy 2018-19  73 non-null     float64
 4   fy 2019-20  73 non-null     float64
 5   fy 2020-21  73 non-null     float64
 6   fy 2021-22  73 non-null     float64
 7   fy 2022-23  73 non-null     float64
 8   fy 2023-24  73 non-null     float64
 9   july        73 non-null     float64
 10  august      73 non-null     float64
 11  september   73 non-null     float64
dtypes: float64(10), object(2)
memory usage: 7.0+ KB

In [41]:
df.describe()

1,fy 2017-18,fy 2018-19,fy 2019-20,fy 2020-21,fy 2021-22,fy 2022-23,fy 2023-24,july,august,september
count,73.000000,73.000000,73.000000,73.000000,73.000000,73.000000,73.000000,73.000000,73.000000,73.000000
mean,615.694521,674.782192,748.154795,1018.261644,864.323288,888.110959,982.693151,78.647945,91.404110,98.802740
std,1953.327032,2143.627590,2399.534131,3345.409161,2815.706003,2924.756117,3276.719061,265.390269,301.313522,322.424157
min,14.600000,15.700000,12.900000,16.900000,16.200000,19.900000,18.600000,1.100000,1.500000,1.800000
25%,57.000000,60.000000,66.800000,86.500000,76.000000,60.800000,62.500000,4.400000,7.500000,8.600000
50%,130.900000,143.100000,160.300000,198.100000,171.800000,128.000000,130.900000,9.900000,15.000000,18.200000
75%,343.000000,361.700000,391.800000,497.600000,452.600000,382.100000,391.700000,31.600000,41.600000,46.800000
max,14981.900000,16419.700000,18205.100000,24777.700000,21031.700000,21610.700000,23912.200000,1913.800000,2224.200000,2404.100000

In [42]:
df.memory_usage(deep=True)

Index          132
division      2553
district      4207
fy 2017-18     584
fy 2018-19     584
fy 2019-20     584
fy 2020-21     584
fy 2021-22     584
fy 2022-23     584
fy 2023-24     584
july           584
august         584
september      584
dtype: int64

In [49]:
missing = df.isna().sum()
missing

1
district      1
fy 2017-18    0
fy 2018-19    0
fy 2019-20    0
fy 2020-21    0
fy 2021-22    0
fy 2022-23    0
fy 2023-24    0
july          0
august        0
september     0
dtype: int64

In [46]:
df.drop(columns='division' , inplace=True)

In [47]:
df.isna().sum()

1
district      1
fy 2017-18    0
fy 2018-19    0
fy 2019-20    0
fy 2020-21    0
fy 2021-22    0
fy 2022-23    0
fy 2023-24    0
july          0
august        0
september     0
dtype: int64

In [52]:
missing_percentage = 100*missing/len(df)
missing_percentage

1
district      1.369863
fy 2017-18    0.000000
fy 2018-19    0.000000
fy 2019-20    0.000000
fy 2020-21    0.000000
fy 2021-22    0.000000
fy 2022-23    0.000000
fy 2023-24    0.000000
july          0.000000
august        0.000000
september     0.000000
dtype: float64