In [6]:
import pandas as pd

# DataFrame 1: Customers
customers = pd.DataFrame({
    "customer_id": [101, 102, 103, 104],
    "name": ["Alice", "Bob", "Charlie", "David"],
    "city": ["Dhaka", "Chittagong", "Khulna", "Sylhet"]
})

customers

   customer_id     name        city
0          101    Alice       Dhaka
1          102      Bob  Chittagong
2          103  Charlie      Khulna
3          104    David      Sylhet

In [5]:
# DataFrame 3: Payments
payments = pd.DataFrame({
    "order_id": [1001, 1002, 1005],
    "payment_method": ["Card", "Bkash", "Cash"],
    "amount": [80000, 30000, 500]
})

payments

   order_id payment_method  amount
0      1001           Card   80000
1      1002          Bkash   30000
2      1005           Cash     500

In [4]:
# DataFrame 2: Orders
orders = pd.DataFrame({
    "order_id": [1001, 1002, 1003, 1004],
    "customer_id": [101, 102, 101, 105],
    "product": ["Laptop", "Phone", "Keyboard", "Mouse"]
})

orders

   order_id  customer_id   product
0      1001          101    Laptop
1      1002          102     Phone
2      1003          101  Keyboard
3      1004          105     Mouse

In [14]:
#1. Show all customer names with their ordered products
pd.merge(customers , orders ,on="customer_id",how = "inner" )[['name','product']]

      name   product
0    Alice    Laptop
1    Alice  Keyboard
2      Bob     Phone
3  Charlie       NaN
4    David       NaN

In [24]:
# 2. Find customers who did not place any order
no_order = pd.merge(customers , orders ,on="customer_id",how = "left" )[['name','product']]
no_order[no_order['product'].isnull()]

      name product
3  Charlie     NaN
4    David     NaN

In [30]:
# 3. Find orders that do not have customer information
third = pd.merge(customers , orders ,on="customer_id",how = "right" )[['customer_id','name','product']]
third[third['name'].isna()]

   customer_id name product
3          105  NaN   Mouse

In [36]:
#4. Show all orders with payment amount
pd.merge(orders, payments, on='order_id', how='inner')[
    ['order_id', 'product', 'amount']
]

   order_id product  amount
0      1001  Laptop   80000
1      1002   Phone   30000

In [42]:
#5. Find products that are not paid yet
five = pd.merge(orders, payments, on='order_id', how='left')[
    ['order_id', 'product', 'amount']
]
five[five['amount'].isna()]

   order_id   product  amount
2      1003  Keyboard     NaN
3      1004     Mouse     NaN

In [ ]:
#6. Create one final DataFrame containing

In [ ]:
#7. Count how many orders each customer made

In [ ]:
#8. Find total payment amount by each customer

In [ ]:
#9. Show customers from Dhaka with their orders

In [ ]:
#10. Find unpaid customers