In [4]:
import pandas as pd
import numpy as np

# DataFrame 1: Customers
customers = pd.DataFrame({
    "customer_id": [101, 102, 103, 104],
    "name": ["Alice", "Bob", "Charlie", "David"],
    "city": ["Dhaka", "Chittagong", "Khulna", "Sylhet"]
})

customers

   customer_id     name        city
0          101    Alice       Dhaka
1          102      Bob  Chittagong
2          103  Charlie      Khulna
3          104    David      Sylhet

In [6]:
# DataFrame 3: Payments
payments = pd.DataFrame({
    "order_id": [1001, 1002, 1005],
    "payment_method": ["Card", "Bkash", "Cash"],
    "amount": [80000, 30000, 500]
})

payments

   order_id payment_method  amount
0      1001           Card   80000
1      1002          Bkash   30000
2      1005           Cash     500

In [7]:
# DataFrame 2: Orders
orders = pd.DataFrame({
    "order_id": [1001, 1002, 1003, 1004],
    "customer_id": [101, 102, 101, 105],
    "product": ["Laptop", "Phone", "Keyboard", "Mouse"]
})

orders

   order_id  customer_id   product
0      1001          101    Laptop
1      1002          102     Phone
2      1003          101  Keyboard
3      1004          105     Mouse

In [14]:
#1. Show all customer names with their ordered products
pd.merge(customers , orders ,on="customer_id",how = "inner" )[['name','product']]

      name   product
0    Alice    Laptop
1    Alice  Keyboard
2      Bob     Phone
3  Charlie       NaN
4    David       NaN

In [24]:
# 2. Find customers who did not place any order
no_order = pd.merge(customers , orders ,on="customer_id",how = "left" )[['name','product']]
no_order[no_order['product'].isnull()]

      name product
3  Charlie     NaN
4    David     NaN

In [30]:
# 3. Find orders that do not have customer information
third = pd.merge(customers , orders ,on="customer_id",how = "right" )[['customer_id','name','product']]
third[third['name'].isna()]

   customer_id name product
3          105  NaN   Mouse

In [36]:
#4. Show all orders with payment amount
pd.merge(orders, payments, on='order_id', how='inner')[
    ['order_id', 'product', 'amount']
]

   order_id product  amount
0      1001  Laptop   80000
1      1002   Phone   30000

In [42]:
#5. Find products that are not paid yet
five = pd.merge(orders, payments, on='order_id', how='left')[
    ['order_id', 'product', 'amount']
]
five[five['amount'].isna()]

   order_id   product  amount
2      1003  Keyboard     NaN
3      1004     Mouse     NaN

In [11]:
# #6. Create one final DataFrame containing 
# customer name
# city
# product
# payment method
# amount

six = customers.merge(orders , on='customer_id',how='outer').merge(payments, on='order_id', how='outer')[['name' , 'city' , 'product', 'payment_method','amount']]
six

      name        city   product payment_method   amount
0    Alice       Dhaka    Laptop           Card  80000.0
1      Bob  Chittagong     Phone          Bkash  30000.0
2    Alice       Dhaka  Keyboard            NaN      NaN
3      NaN         NaN     Mouse            NaN      NaN
4      NaN         NaN       NaN           Cash    500.0
5  Charlie      Khulna       NaN            NaN      NaN
6    David      Sylhet       NaN            NaN      NaN

In [20]:
#7. Count how many orders each customer made
seven = customers.merge(orders , on='customer_id',how='outer').merge(payments, on='order_id', how='outer')
seven.groupby('name')['order_id'].count()

name
Alice      2
Bob        1
Charlie    0
David      0
Name: order_id, dtype: int64

In [21]:
#8. Find total payment amount by each customer
seven.groupby('name')['amount'].sum()

name
Alice      80000.0
Bob        30000.0
Charlie        0.0
David          0.0
Name: amount, dtype: float64

In [24]:
#9. Show customers from Dhaka with their orders
seven[seven['city']=='Dhaka'][['name', 'city','product']]

    name   city   product
0  Alice  Dhaka    Laptop
2  Alice  Dhaka  Keyboard

In [39]:
#10. Find unpaid customers
temp = customers.merge(orders, on='customer_id', how='inner') \
                .merge(payments, on='order_id', how='left')

temp[temp['amount'].isna()][['name','product']]

    name   product
1  Alice  Keyboard